//---------------------------------------------------------------------------------------------
// Reference ... prog[0] won't be used. It's just an example.
// Look in program.js to see explanation of these properties.
//---------------------------------------------------------------------------------------------  
// pn=0;    // start value for prog numbering
// prog[pn]=['ProgramName'];
// ordr[pn]=[0];
// desc[pn]=['Description'];
// uid[pn]=['APP1'];
// dflt[pn]=['no'];
// cat[pn]=['Application Category'];
// forc[pn]=['false'];
// configs[pn]=['List of configs to be auto checked. Comma seperated'];
// deps[pn]=[];
// excl[pn]=[];
// cond[pn]=['Javascript Conditional Statement'];
// gcond[pn]=['Javascript Conditional Statement to gray item'];
// regb[pn]=['Registry Key Path'];
// cmd1[pn]=['CommandLine 1'];
// cmd2[pn]=['CommandLine 2'];
// cmd3[pn]=['CommandLine 3'];
// cmd4[pn]=['CommandLine 4'];
// cmd5[pn]=['CommandLine 5'];
// cmd6[pn]=['CommandLine 6'];
// rega[pn]=['Registry Key Path'];
// picf[pn]=['Picture File'];
// picw[pn]=['Width'];
// pich[pn]=['Height'];
// textl[pn]=['Text Location'];
// pn++;

//---------------------------------------------------------------------------------------------
// Your programs here ...
//---------------------------------------------------------------------------------------------
pn=1;
prog[pn]=['Disable SystemRestore'];
ordr[pn]=[101];
desc[pn]=['Disable SystemRestore'];
uid[pn]=['DISABLESYSTEMRESTORE'];
dflt[pn]=['yes'];
cat[pn]=['Registry Tweaks'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
regb[pn]=['%wpipath%\\Install\\RegFiles\\Disable_SystemRestore.reg'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['HKCU Explorer Tweaks'];
ordr[pn]=[102];
desc[pn]=['Registry entries: Show Status Bar     , Disable AutoTray, Show Hidden Files, Show File Ext, Show StartMenu Netwerklocaties,  Show StartMenu Netwerkverbindingen, Niet Desktop Opruimen, Open .nfo en .sif met Wordpad, Explorer Details'];
uid[pn]=['HKCUEXPLORERTWEAKS'];
dflt[pn]=['no'];
cat[pn]=['Registry Tweaks'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
regb[pn]=['%wpipath%\\Install\\RegFiles\\HKCU_Explorer_Tweaks.reg'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['CmdHere'];
ordr[pn]=[103];
desc[pn]=['CmdHere Tweak'];
uid[pn]=['CMDHERE'];
dflt[pn]=['no'];
cat[pn]=['Registry Tweaks'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
regb[pn]=['%wpipath%\\Install\\RegFiles\\CmdHere.reg'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;
// 
// prog[pn]=['NoLowDiskSpaceChecks'];
// ordr[pn]=[104];
// desc[pn]=['NoLowDiskSpaceChecks Tweak'];
// uid[pn]=['NOLOWDISKSPACECHECKS'];
// dflt[pn]=['no'];
// cat[pn]=['Registry Tweaks'];
// forc[pn]=['no'];
// configs[pn]=['yes'];
// gcond[pn]=['FileExists(\'%programfiles%\\\')'];
// regb[pn]=['%wpipath%\\Install\\RegFiles\\NoLowDiskSpace.reg'];
// picf[pn]=['regedit.png'];
// picw[pn]=['128'];
// pich[pn]=['128'];
// textl[pn]=['Top'];
// pn++;

prog[pn]=['WindowsUpdate_DownloadOnly'];
ordr[pn]=[105];
desc[pn]=['WindowsUpdate_DownloadOnly'];
uid[pn]=['WindowsUpdate_DownloadOnly'];
dflt[pn]=['yes'];
cat[pn]=['Registry Tweaks'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
regb[pn]=['%wpipath%\\Install\\RegFiles\\WindowsUpdate_DownloadOnly.reg'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['IE7 Tweaks'];
ordr[pn]=[106];
desc[pn]=['IE7 Tweaks'];
uid[pn]=['IE7 Tweaks'];
dflt[pn]=['yes'];
cat[pn]=['Registry Tweaks'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
regb[pn]=['%wpipath%\\Install\\RegFiles\\IE7_Tweaks.reg'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['ERUNT 1.1j'];
ordr[pn]=[200];
desc[pn]=['ERUNT Registry Backup and Restore Utility'];
uid[pn]=['ERUNT'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\ERUNT-SETUP.EXE /VERYSILENT'];
picf[pn]=['ERUNT.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['ExplorerXP 1.07'];
ordr[pn]=[201];
desc[pn]=['ExplorerXP is a small File Manager with display of folder size. It allows you to browse multiple folders from a tabbed interface.'];
uid[pn]=['EXPXP'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\EXPLORERXPSETUP.EXE /S'];
picf[pn]=['explorerxp.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['DISKdata v3.5.0'];
ordr[pn]=[202];
desc[pn]=['DISKdata v3.5.0 is a powerful explorer-like application for Windows 95/98/ME/NT/2000/XP/2003/Vista that analyzes disk space utilization.'];
uid[pn]=['DISKDATA'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\DISKDATA.MSI /qn'];
// rega[pn]=['%wpipath%\\Install\\RegFiles\\DiskData.reg'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['DVD Decrypter 3.5.4.0'];
ordr[pn]=[203];
desc[pn]=['DVD Decrypter is a highly versatile VOB-ripping utility. The software takes advantage of both the DeCSS Plus and VobDec algorithms for looking up and decrypting the CSS encryption. DVD Decrypter is also multi-angle aware, and capable of removing the Macrovision scrambling key, as well as the region code during the ripping process.'];
uid[pn]=['DVD'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\SETUPDVDDECRYPTER_3.5.4.0.EXE /S'];
picf[pn]=['LaST (Cobalt) DVD.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['DVD Shrink 3.2'];
ordr[pn]=[204];
desc[pn]=['DVD Shrink enables you to copy a DVD very easily. Copying a DVD doesn\'t get much simpler than this. Put DVD into DVD-ROM or DVD burner. Choose either a Full Disk (1:1) copy or a main movie only. It\'ll analyze DVD, encode video files , and finally burn a copy of the dvd to DVD±R media. Thus you have a excellent quality dvd copy of your original DVD.'];
uid[pn]=['Shrink'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\DVDSHRINK32SETUP.EXE /VERYSILENT /NORESTART'];
picf[pn]=['CDs.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['IsoBuster 1.9.1'];
ordr[pn]=[205];
desc[pn]=['ISOBUSTER makes ISO-file from CD or DVD. The Ultimate CD/DVD and BD/HD DVD data recovery software. Explore a CD file system bypassing Windows'];
uid[pn]=['ISOBUSTER'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\ISOBUSTER191_ML.EXE /VERYSILENT /SP- /DIR="C:\\Program Files\\IsoBuster" /GROUP="IsoBuster"'];
cmd2[pn]=['%wpipath%\\Install\\pskill.exe isobuster.exe'];
picf[pn]=['ISOBUSTER.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['WinAmp 5.24 Pro + 3 Plugins'];
ordr[pn]=[206];
desc[pn]=['WinAmp 5.24 Pro Audio mp3-Player, Extra Plugins: Flac, Musepack en APE'];
uid[pn]=['WinAmp'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\Winamp_524.exe /S /install=R'];
cmd2[pn]=['%wpipath%\\Install\\pskill.exe winamp.exe'];
cmd3[pn]=['FileCopy "%wpipath%\\Install\\WinAmp_Plugins\\*.*" "C:\\Program Files\\Winamp\\Plugins"'];
cmd4[pn]=['FileCopy "%wpipath%\\Install\\Winamp.ini" "C:\\Program Files\\Winamp"'];
// rega[pn]=['%wpipath%\\Install\\RegFiles\\WinAmp.reg'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Power Archiver 2007 10.00.42'];
ordr[pn]=[207];
desc[pn]=['Power Archiver is an archive utility that provides support for ZIP, 7-Zip, CAB, RAR(unpack only) and other formats. Create powerful self-extracting (SFX) archives'];
uid[pn]=['PowerArchiver'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\PowerArchiver_2007\\powarc1001.exe /quiet'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['7-Zip 4.42'];
ordr[pn]=[208];
desc[pn]=['7-Zip Archiver: Packing / unpacking: 7z, ZIP, GZIP, BZIP2 and TAR. Unpacking only: RAR, CAB, ISO, and other formats.'];
uid[pn]=['7ZIP'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\7Z442.EXE /S'];
picf[pn]=['7z.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['WinRAR v3.62 Corp'];
ordr[pn]=[209];
desc[pn]=['WinRAR is an Archiver: RAR and ZIP compression and decompression. RAR compression with Split to Volumes Option. Creates self-extracting archives (SFX)'];
uid[pn]=['WINRAR362C'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\WinRAR_362Corp.exe /S'];
picf[pn]=['Winrar1.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Irfan View 3.97'];
ordr[pn]=[210];
desc[pn]=['Irfan View: View and edit most graphics formats available today in a fast and simple way. Easy SlideShow'];
uid[pn]=['IrfanView'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\IRFANVIEW\\IVIEW397.EXE /silent /desktop=1 /group=1 /allusers=1 /assoc=0'];
cmd2[pn]=['%wpipath%\\Install\\IRFANVIEW\\IRFANVIEW_PLUGINS_397.EXE /silent'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['SyncBack 3.2.8.400'];
ordr[pn]=[211];
desc[pn]=['SyncBack is used to back-up and restore, files and directories, whether they be on a local drive, a network drive, an FTP server, a ZIP archive, or on removable media.'];
uid[pn]=['SyncBack'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\SYNCBACK_SETUP.EXE /VERYSILENT /DIR="C:\\Program Files\\SyncBack" /GROUP="SyncBack"'];
picf[pn]=['syncfolder.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Total Commander 6.56'];
ordr[pn]=[213];
desc[pn]=['Total Commander 6.56'];
uid[pn]=['TotalCommander'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\tcmdr656\\INSTALL.EXE'];
cmd2[pn]=['FileCopy "%wpipath%\\Install\\tcmdr656\\Wincmd.key" "C:\\Program Files\\TotalCommander"'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['UltraVNC 1.0.2'];
ordr[pn]=[214];
desc[pn]=['UltraVNC can display the screen of another computer (via internet or network) on your own screen.'];
uid[pn]=['ULTRAVNC'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\ULTRAVNC-102-SETUP.EXE /verysilent'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Tiny Hexer 1.8.1.2'];
ordr[pn]=[215];
desc[pn]=['Tiny Hexer - free hex editor with disk editor'];
uid[pn]=['TinyHexer'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\mpth_18.exe /VERYSILENT /SP- /DIR="C:\\Program Files\\TinyHexer" /GROUP="TinyHexer"'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['UltraEdit 12.20b'];
ordr[pn]=[216];
desc[pn]=['UltraEdit 12.20b'];
uid[pn]=['UltraEdit'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\uesetup.exe -s'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['UltraCompare Professional 4.20a'];
ordr[pn]=[217];
desc[pn]=['UltraCompare Professional 4.20a'];
uid[pn]=['UltraCompare'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\ucsetup.exe -s'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Spybot 1.5.2'];
ordr[pn]=[218];
desc[pn]=['Spybot blocks and removes Spyware.'];
uid[pn]=['SPYBOT'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\spybotsd152.exe /verysilent /noreboot'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;
// 
// prog[pn]=['QuickTime'];
// ordr[pn]=[219];
// desc[pn]=['QuickTime MOV Player'];
// uid[pn]=['QuickTime'];
// dflt[pn]=['no'];
// cat[pn]=['System'];
// forc[pn]=['no'];
// configs[pn]=['yes'];
// gcond[pn]=['FileExists(\'%programfiles%\\\')'];
// cmd1[pn]=['%wpipath%\\Install\\QuickTimeInstaller.exe /quiet'];
// picf[pn]=['InstallPackage.png'];
// picw[pn]=['128'];
// pich[pn]=['128'];
// textl[pn]=['Top'];
// pn++;
// 
// prog[pn]=['Skype 3.0.0.218'];
// ordr[pn]=[221];
// desc[pn]=['Skype 3.0.0.218'];
// uid[pn]=['Skype'];
// dflt[pn]=['no'];
// cat[pn]=['System'];
// forc[pn]=['no'];
// configs[pn]=['yes'];
// gcond[pn]=['FileExists(\'%programfiles%\\\')'];
// cmd1[pn]=['%wpipath%\\Install\\SKYPESETUP.EXE /VERYSILENT /nogoogle'];
// cmd2[pn]=['%wpipath%\\Install\\pskill.exe SKYPE.exe'];
// picf[pn]=['InstallPackage.png'];
// picw[pn]=['128'];
// pich[pn]=['128'];
// textl[pn]=['Top'];
// pn++;
// 
// prog[pn]=['Adobe Reader 8'];
// ordr[pn]=[222];
// desc[pn]=['Adobe Reader 8  PDF Viewer'];
// uid[pn]=['AdobeReader'];
// dflt[pn]=['yes'];
// cat[pn]=['System'];
// forc[pn]=['no'];
// configs[pn]=['yes'];
// gcond[pn]=['FileExists(\'%programfiles%\\\')'];
// cmd1[pn]=['%wpipath%\\Install\\AdbeRdr80_nl_NL.exe /sPB'];
// picf[pn]=['InstallPackage.png'];
// picw[pn]=['128'];
// pich[pn]=['128'];
// textl[pn]=['Top'];
// pn++;

prog[pn]=['Nero 6.6.1.4 + Audio Plugins'];
ordr[pn]=[223];
desc[pn]=['Nero Burning ROM 6.6.1.4 + WMA and Cole2k Audio Plugins'];
uid[pn]=['Nero6'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\Nero6_Upd_Eng\\Nero_6614.exe /SN=XXXX-XXXX-XXXX-XXXX-XXXX-XXXX /WRITE_SN /SILENT /NO_UI /NOREBOOT /NOLICENSE /NOCANCEL'];
cmd2[pn]=['%wpipath%\\Install\\Nero6_Upd_Eng\\WMAPlugin20937.exe /SILENT /NO_UI'];
cmd3[pn]=['%wpipath%\\Install\\Nero6_Upd_Eng\\Cole2k_NeroAudioPlugin153_Setup.exe /S'];
cmd4[pn]=['%wpipath%\\INSTALL_NERO_HELP.BAT'];
picf[pn]=['NERO1.PNG'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Sygate Personal Firewall 5.6'];
ordr[pn]=[225];
desc[pn]=['Sygate Personal Firewall protects your PC from hackers, Trojans, and malicious code intrusions.'];
uid[pn]=['SPF'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\FIREWALL_SPF.EXE /QN Reboot=Suppress'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Avast! 4 Home Edition 4.7.1098'];
ordr[pn]=[226];
desc[pn]=['Avast! 4 Home Edition is a full-featured AntiVirus package.'];
uid[pn]=['AVAST47'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\AVAST_setupeng.exe /VERYSILENT /SP-'];
picf[pn]=['InstallPackage.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Purge DLL Cache'];
ordr[pn]=[290];
desc[pn]=['Purge DLL Cache'];
uid[pn]=['DLLCACHEPURGE'];
dflt[pn]=['no'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
cmd1[pn]=['%wpipath%\\Install\\RegFiles\\SFC_DLLCACHE.BAT'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

prog[pn]=['Enable SystemRestore'];
ordr[pn]=[291];
desc[pn]=['Enable SystemRestore'];
uid[pn]=['ENABLESYSTEMRESTORE'];
dflt[pn]=['yes'];
cat[pn]=['System'];
forc[pn]=['no'];
configs[pn]=['yes'];
gcond[pn]=['FileExists(\'%programfiles%\\\')'];
regb[pn]=['%wpipath%\\Install\\RegFiles\\Enable_SystemRestore.reg'];
picf[pn]=['regedit.png'];
picw[pn]=['128'];
pich[pn]=['128'];
textl[pn]=['Top'];
pn++;

//---------------------------------------------------------------------------------------------
// End of program definitions ...
//---------------------------------------------------------------------------------------------
